# Generated by Django 5.1 on 2024-08-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, db_column='region', max_length=250, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=50, null=True)),
                ('itemtype', models.CharField(blank=True, db_column='itemtype', max_length=50, null=True)),
                ('saleschannel', models.CharField(blank=True, db_column='saleschannel', max_length=50, null=True)),
                ('orderpriority', models.CharField(blank=True, db_column='orderpriority', max_length=50, null=True)),
                ('orderdate', models.DateField(blank=True, db_column='orderdate', null=True)),
                ('orderid', models.IntegerField(blank=True, db_column='orderid', null=True)),
                ('shipdate', models.DateField(blank=True, db_column='shipdate', null=True)),
                ('unitssold', models.IntegerField(blank=True, db_column='unitssold', null=True)),
                ('unitprice', models.FloatField(blank=True, db_column='unitprice', null=True)),
                ('unitcost', models.FloatField(blank=True, db_column='unitcost', null=True)),
                ('totalrevenue', models.FloatField(blank=True, db_column='totalrevenue', editable=False, null=True)),
                ('totalcost', models.FloatField(blank=True, db_column='totalcost', editable=False, null=True)),
                ('totalprofit', models.FloatField(blank=True, db_column='totalprofit', editable=False, null=True)),
            ],
            options={
                'db_table': 'Salesrecord',
                'managed': False,
            },
        ),
    ]
